disable-require = false

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
debug = "/var/log/nvidia-container-cli.log"
ldcache = "/usr/local/glibc/etc/ld.so.cache"
ldconfig = "@/usr/local/glibc/sbin/ldconfig"
load-kmods = false
#no-cgroups = false
#user = "root:video"

[nvidia-container-runtime]
debug = "/var/log/nvidia-container-runtime.log"
